In [1]:
import numpy as np
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [2]:
fp_df = pd.read_csv('Faceplate.csv',index_col=0)
fp_df=fp_df.astype(bool)
fp_df.head()

               Red  White   Blue  Orange  Green  Yellow
Transaction
1             True   True  False   False   True   False
2            False   True  False    True  False   False
3            False   True   True   False  False   False
4             True   True  False    True  False   False
5             True  False   True   False  False   False

In [3]:
# Create frequent itemsets
itemsets=apriori(fp_df,min_support=0.2,use_colnames=True)

In [4]:
itemsets

    support             itemsets
0       0.6                (Red)
1       0.7              (White)
2       0.6               (Blue)
3       0.2             (Orange)
4       0.2              (Green)
5       0.4         (White, Red)
6       0.4          (Red, Blue)
7       0.2         (Red, Green)
8       0.4        (White, Blue)
9       0.2      (White, Orange)
10      0.2       (White, Green)
11      0.2   (White, Red, Blue)
12      0.2  (White, Red, Green)

In [11]:
# and convert into rules
rules=association_rules(itemsets,metric='confidence',min_threshold=0.6)
rules=rules[['antecedents','consequents','support','confidence','lift']]
rules=rules[rules['lift']>1]
rules.sort_values(by='lift',ascending=False)

      antecedents   consequents  support  confidence      lift
1           (Red)        (Blue)      0.4    0.666667  1.111111
2          (Blue)         (Red)      0.4    0.666667  1.111111
3         (Green)         (Red)      0.2    1.000000  1.666667
5        (Orange)       (White)      0.2    1.000000  1.428571
6         (Green)       (White)      0.2    1.000000  1.428571
7    (Red, Green)       (White)      0.2    1.000000  1.428571
8  (Green, White)         (Red)      0.2    1.000000  1.666667
9         (Green)  (Red, White)      0.2    1.000000  2.500000

In [14]:
#FOR min_support=0.3
# Create frequent itemsets
itemsets=apriori(fp_df,min_support=0.3,use_colnames=True)
# and convert into rules
rules=association_rules(itemsets,metric='confidence',min_threshold=0.6)
rules=rules[['antecedents','consequents','support','confidence','lift']]
rules=rules[rules['lift']>1]
rules.sort_values(by='lift',ascending=False)

  antecedents consequents  support  confidence      lift
1       (Red)      (Blue)      0.4    0.666667  1.111111
2      (Blue)       (Red)      0.4    0.666667  1.111111

In [16]:
#FOR min_support=0.4
# Create frequent itemsets
itemsets=apriori(fp_df,min_support=0.4,use_colnames=True)
# and convert into rules
rules=association_rules(itemsets,metric='confidence',min_threshold=0.6)
rules=rules[['antecedents','consequents','support','confidence','lift']]
rules=rules[rules['lift']>1]
rules.sort_values(by='lift',ascending=False)

  antecedents consequents  support  confidence      lift
1       (Red)      (Blue)      0.4    0.666667  1.111111
2      (Blue)       (Red)      0.4    0.666667  1.111111

## USING GRADIO

In [19]:
def gen_rules(min_sup,min_coef):
    itemsets=apriori(fp_df,min_support=min_sup,use_colnames=True)
    #and convert into rules
    rules=association_rules(itemsets,metric='confidence',min_threshold=min_coef)
    rules=rules[['antecedents','consequents','support','confidence','lift']]
    rules=rules[rules['lift']>1]
    return rules.sort_values(by='lift',ascending=False)

In [20]:
import gradio as gr
demo=gr.Interface(gen_rules,
                 inputs=[gr.Number(value=0.01,step=0.01,minimum=0.0001,maximum=1),
                        gr.Number(value=0.01,step=0.01,minimum=0.0001,maximum=1)],
                 outputs='dataframe')

if __name__=="__main__":
    demo.launch()

Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.